name = "chocolate_bar2410/numluau"
version = "1.0.0"
description = "numluau (numerical luau), a scientific computing library for luau. Handle N-Dimensional arrays and compute linear algebra easily."
repository = "https://github.com/chocolate-bar2410/numluau"
authors = ["chocolate_bar2410 <https://github.com/chocolate-bar2410>"]
license = "MIT"

includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "numluau/**",
]

[target]
environment = "luau"
lib = "numluau/numluau.luau"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"

[dependencies]