name = "chocolate_bar2410/numluau"
version = "1.1.1"
description = "Numerical luau for all your scientific urges. Bring scientific computing in a way easy to understand and predict."
repository = "https://github.com/chocolate-bar2410/numluau"
authors = ["chocolate_bar2410"]
license = "MIT"

includes = ["pesde.toml", "README.md", "LICENSE", "numluau/**"]

[target]
environment = "luau"
lib = "numluau/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
