name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write

env:
  NUMLUAU_VERSION: v1.1
  NUMLUAU_DEPLOY_TYPE: 'release'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: install zensical
        run: pip install zensical

      - name: install mike
        run: pip install git+https://github.com/squidfunk/mike.git

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: git fetch origin gh-pages --depth=1

      - name: deploy latest
        if: env.NUMLUAU_DEPLOY_TYPE == 'release'
        run: mike deploy $NUMLUAU_VERSION latest -u -b gh-pages

      - name: set default version to latest
        if: env.NUMLUAU_DEPLOY_TYPE == 'release'
        run: mike set-default latest -b gh-pages -p

      - name: deploy dev
        if: env.NUMLUAU_DEPLOY_TYPE == 'dev'
        run: mike deploy $NUMLUAU_VERSION -u -b gh-pages -p
